# Generated by Django 5.2.4 on 2026-02-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_custome_6c3a7f_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_table_i_50e4d9_idx",
        ),
    ]
