# Generated by Django 5.2.4 on 2026-02-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "customers",
                "indexes": [
                    models.Index(fields=["email"], name="customers_email_92e882_idx"),
                    models.Index(
                        fields=["phone_number"], name="customers_phone_n_7d2329_idx"
                    ),
                ],
            },
        ),
    ]
