"""
Django settings for tableTapBackend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from mongoengine import connect

env_name = os.getenv("DJANGO_ENV", "development")

if env_name == "production":
    dotenv_path = ".prod.env"
else:
    dotenv_path = ".dev.env"

load_dotenv(dotenv_path=".dev.env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-kg=oaw*&jl0ced8(3(on34(3vo%^ygrrd*aim^4y%yyj&r==$^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
print("DEBUG mode is:", DEBUG)

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")

CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOW_CREDENTIALS = True

# Application definition
INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "tableTapBackend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "tableTapBackend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "tableTapBackend.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Database - Mongodb
# Used for document based data(primarly used for patient data for now)
MONGO_URI = os.environ.get("MONGO_URI", "mongodb://mongo:27017")

# Check if any commands have the word 'test' in them
TESTING = "test" in sys.argv

# Check is testing is true and set matching database table name
if TESTING:
    print("=========Testing mode=========")
    MONGO_DB_NAME = "TableTap_Test_MongoDB"
else:
    print("Dev mode")
    MONGO_DB_NAME = "TableTap_MongoDB"

FULL_MONGO_URI = f"{MONGO_URI}/{MONGO_DB_NAME}"

# Attempt to connect to mongodb database
try:
    connect(
        db=MONGO_DB_NAME,
        host=MONGO_URI,
        port=int(os.getenv("MONGO_PORT", 27017)),
        username=os.getenv("MONGO_USER"),
        password=os.getenv("MONGO_PASS"),
        authentication_source=os.getenv("MONGO_AUTH_SOURCE", "admin"),
    )
    print("Connected successfully to:", MONGO_DB_NAME)
except Exception as e:
    print({"Message:": f"Failed to connect to {MONGO_DB_NAME}", "Error:": str(e)})

# If testing is true, it will attempt to create a test collection to make sure it can be accessed
if TESTING:
    from mongoengine import Document, StringField

    class TestDoc(Document):
        name = StringField()
        meta = {"collection": "test_collection"}

    try:
        TestDoc(name="test").save()
        print("Added TestDoc successfully")
    except Exception as e:
        print(f"Failed to create test document: {e}")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Check if backend is running for production or development
if DEBUG:
    #  Use MailHog for development
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "mailhog"
    EMAIL_PORT = 1025
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""

else:
    # Use Gmail SMTP for production
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")  # sender's email-id
    EMAIL_HOST_PASSWORD = os.environ.get(
        "EMAIL_HOST_PASSWORD"
    )  # password associated with above email-id (not the regular password)

    # Validate it is correct
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        raise ValueError(
            "EMAIL_HOST_USER and EMAIL_HOST_PASSWORD must be set in production."
        )
