# Generated by Django 5.2.4 on 2026-02-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.PositiveIntegerField()),
                ("qr_code_string", models.CharField(max_length=255, unique=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "tables",
                "indexes": [
                    models.Index(
                        fields=["qr_code_string"], name="tables_qr_code_1cc796_idx"
                    )
                ],
                "unique_together": {("restaurant", "table_number")},
            },
        ),
    ]
