# Generated by Django 5.2.4 on 2026-02-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="menuitem",
            name="menu_items_restaur_938808_idx",
        ),
    ]
