# Generated by Django 5.2.4 on 2026-03-07 21:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_remove_menuitem_menu_items_restaur_938808_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="restaurant",
        ),
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "menu_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_categories",
                        to="menus.menu",
                    ),
                ),
            ],
            options={
                "db_table": "menu_category",
            },
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menus.menucategory",
            ),
        ),
        migrations.AddIndex(
            model_name="menucategory",
            index=models.Index(
                fields=["menu_id", "is_available"],
                name="menu_catego_menu_id_3b9c2a_idx",
            ),
        ),
    ]
