# Generated by Django 5.2.4 on 2026-03-07 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_remove_menuitem_restaurant_menucategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menus.menucategory",
            ),
        ),
    ]
