# Generated by Django 5.2.4 on 2026-03-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_alter_menuitem_category_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="menucategory",
            name="menu_catego_menu_id_3b9c2a_idx",
        ),
        migrations.RemoveIndex(
            model_name="menuitem",
            name="menu_items_menu_id_0aacfa_idx",
        ),
        migrations.RemoveField(
            model_name="menucategory",
            name="menu_id",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="category_id",
        ),
        migrations.AddField(
            model_name="menucategory",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="menus.menu",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menus.menucategory",
            ),
        ),
        migrations.AddIndex(
            model_name="menucategory",
            index=models.Index(
                fields=["menu", "is_available"], name="menu_catego_menu_id_a0c290_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["menu", "category", "is_available"],
                name="menu_items_menu_id_033893_idx",
            ),
        ),
    ]
