# Generated by Django 5.2.4 on 2026-03-07 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0005_remove_menucategory_menu_catego_menu_id_3b9c2a_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menucategory",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="menus.menu",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menus.menucategory",
            ),
        ),
    ]
